# Generated by Django 5.0.6 on 2024-07-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_additional_image_additional_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_image',
            new_name='AdditionalImage',
        ),
        migrations.RenameModel(
            old_name='Additional_information',
            new_name='AdditionalInformation',
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='home.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=555, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='home.subcategory'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
