# Generated by Django 5.0.6 on 2024-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_additional_image_additionalimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
    ]
