# Generated by Django 5.0.6 on 2024-07-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hottrendingproducts_onsaleproducts_topdealsoftheday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopFeaturedProducts',
        ),
    ]
