# Generated by Django 5.0.6 on 2024-07-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
