# Generated by Django 5.0.6 on 2024-07-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_available',
            field=models.PositiveIntegerField(blank=True, default=True, null=True),
        ),
    ]
