# Generated by Django 5.0.6 on 2024-07-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_product_product_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalImage',
            new_name='Additional_image',
        ),
        migrations.RenameModel(
            old_name='AdditionalInformation',
            new_name='Additional_information',
        ),
    ]
