# Generated by Django 5.0.6 on 2024-07-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_additionalimage_additional_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_image',
            new_name='AdditionalImage',
        ),
        migrations.RenameModel(
            old_name='Additional_information',
            new_name='AdditionalInformation',
        ),
    ]
