# Generated by Django 5.0.6 on 2024-07-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_hottrendingproducts_onsaleproducts_topdealsoftheday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='mainCategory',
        ),
        migrations.DeleteModel(
            name='mainCategory',
        ),
    ]
